Library Managment/Library Managment/Areas/Admin/Controllers/AdminHomeController.cs
using Library_Managment.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Library_Managment.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Library_Managment.Areas.Admin.Models;

namespace Library_Managment.Areas.Admin.Controllers {

    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class AdminHomeController : Controller {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<UserNewData> _userManager;
        public AdminHomeController(ApplicationDbContext context, UserManager<UserNewData> userManager) {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index() {
            return View();
        }

        [HttpPost]
        public IActionResult SearchUser(string search) {
            
            List<UserNewData> users = _context.Users.FromSqlRaw($"SELECT * FROM AspNetUsers WHERE Name LIKE '%{search}%' OR Surname LIKE '%{search}%' OR UserName LIKE '%{search}%'").ToList<UserNewData>();
            return View("DisplayUsers", users);
        }

        public async Task<IActionResult> DisplayUsers(string sortOrder, string currentFilter, string searchString, int? pageNumber) {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null) {
                pageNumber = 1;
            } else {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var users = from s in _context.Users
                        select s;
            if (!String.IsNullOrEmpty(searchString)) {
                users = users.Where(s => s.Name.Contains(searchString)
                                       || s.Surname.Contains(searchString) || s.Email.Contains(searchString) || s.UserName.Contains(searchString));
            }
            switch (sortOrder) {
                case "name_desc":
                    users = users.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    users = users.OrderBy(s => s.Surname);
                    break;
                case "date_desc":
                    users = users.OrderByDescending(s => s.Email);
                    break;
                default:
                    users = users.OrderBy(s => s.UserName);
                    break;
            }

            int pageSize = 10;
            return View(await PaginatedList<UserNewData>.CreateAsync(users.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        
        public async Task<IActionResult> DeleteUser(string Id) {
            var user = _context.Users.First(m => m.Id == Id);

          var DeleteRows = _context.TakenBooks.Where(e => e.UserId == Id).ToList();

            foreach(var row in DeleteRows) {
                _context.TakenBooks.Remove(row);
            }

            _context.Users.Remove(user);
           await _context.SaveChangesAsync();

            return RedirectToAction(nameof(DisplayUsers));
        }


        public async Task<IActionResult> ChangeRoles(string Role, string userId) {

            try {
                if (Role == "Admin") {
                    try {

                        var role = _userManager.FindByIdAsync(userId);

                        var user = await _userManager.FindByIdAsync(userId);

                        await _userManager.RemoveFromRoleAsync(user, "User");
                        await _userManager.AddToRoleAsync(user, "Administrator");
                    } catch (Exception e) {

                        throw e;
                    }

                } else if (Role == "User") {
                    try {

                        var role = _userManager.FindByIdAsync(userId);

                        var user = await _userManager.FindByIdAsync(userId);

                        await _userManager.RemoveFromRoleAsync(user, "Administrator");
                        await _userManager.AddToRoleAsync(user, "User");
                    } catch (Exception e) {

                        throw e;
                    }
                }
            }catch(Exception e) {

            }
            return RedirectToAction(nameof(DisplayUsers));

        }

    }
}

Library Managment/Library Managment/Areas/User/Controllers/UserHomeController.cs
using Library_Managment.Data;
using Library_Managment.Models;
using Library_Managment.Areas.User.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TakenBooks = Library_Managment.Areas.User.Models.TakenBooks;
using Library_Managment.Data.Migrations;
using Library_Managment.Models;
using Library_Managment.Areas.Admin.Models;


namespace Library_Managment.Areas.User.Controllers {

    [Area("User")]
    [Authorize]
    public class UserHomeController : Controller {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<UserNewData> _userManager;
        public UserHomeController(ApplicationDbContext context,UserManager<UserNewData> userManager) {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> IndexAsync(string sortOrder, string currentFilter,string searchString, int? pageNumber) {

     
            List<Book> NewestBooks = (List<Book>)_context.Books.OrderByDescending(x => x.Id).Take(8).ToList<Book>();
            ViewBag.NewestBooks = NewestBooks;

            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
           /* ViewData["Author"] = sortOrder == "author_desc" ? "author_asc" : "author_desc";*/
            ViewData["Drama"] = sortOrder == "Drama" ? "Drama" : "Drama";
            ViewData["Romance"] = sortOrder == "Romance" ? "Romance" : "Romance";
            ViewData["Thriller"] = sortOrder == "Thriller" ? "Thriller" : "Thriller";
            ViewData["Biography"] = sortOrder == "Biography" ? "Biography" : "Biography";

            var books = from s in _context.Books
                        select s;
            switch (sortOrder) {
                case "Drama":
                    books = books.Where(s => s.Genre == "Drama") ;
                    break;
                case "Thriller":
                    books = books.Where(s => s.Genre == "Thriller");
                    break;
                case "Biography":
                    books = books.Where(s => s.Genre == "Biography");
                    break;
                case "Romance":
                    books = books.Where(s => s.Genre == "Romance");
                    break;
                default:
                    books = books;
                    break;
            }

            int pageSize = 8;
            return View(await PaginatedList<Book>.CreateAsync(books.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> BookHistoryAsync() {


            var current = await _userManager.GetUserAsync(User);

            var userRows = _context.TakenBooks.OrderByDescending(x => x.Id).Where(x => x.UserId == current.Id);


            List<TakenBooks> books = new List<TakenBooks>();


            foreach (var row in userRows) {
                var book = _context.Books.Find(row.BookId);

                TakenBooks temp = new TakenBooks {
                    Id = book.Id,
                    ISBN = book.ISBN,
                    Name = book.Name,
                    Description = book.Description,
                    Genre = book.Genre,
                    Author = book.Author,
                    PublishDate = book.PublishDate,
                    Image = book.Image,
                    Amount = book.Amount,
                    Available = book.Available,
                    TakenDate = row.TakenDate,
                    ReturnDate = row.ReturnDate
                };

                books.Add(temp);
            }

            return View(books);
        }

        [HttpPost]
        public IActionResult SearchBook(string searchtext) {
           
            List<Book> books = _context.Books.FromSqlRaw($"SELECT * FROM Books WHERE Name LIKE '%{searchtext}%' OR Author LIKE '%{searchtext}%'").ToList<Book>();

           if(books.Count == 0 || searchtext == null || searchtext.Length <=1) {
                return View("404");
            }

            return View("SearchResults",books);
        }

        public IActionResult BookDetails(int id) {
            Book book = _context.Books.Find(id);
            return View(book);
        }
    }
}

Library Managment/Library Managment/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library_Managment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900" rel="stylesheet">

    <link rel="stylesheet" href="~/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <link rel="stylesheet" href="~/css/aos.css">

    <link rel="stylesheet" href="~/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/icomoon.css">
    <link rel="stylesheet" href="~/css/style.css">

 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

</head>
<body>
    @using Library_Managment.Models;
    @using Microsoft.AspNetCore.Identity;
    @inject UserManager<UserNewData> _userManager;
    @{
        var user = await _userManager.GetUserAsync(User);

        var roles = await _userManager.GetRolesAsync(user);
    }
    <header>

        <nav class="navbar navbar-expand-lg navbar-light navbar-toggleable-sm ftco_navbar bg-light" id="navcstm" style="box-shadow: 0px 1px grey;">
            <div class="container">
                <a class="navbar-brand" asp-area="User" asp-controller="UserHome" asp-action="Index"><span>LMS</span></a>
                <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse">

                    <ul class="navbar-nav nav ml-auto">
                        <li class="nav-item"><a asp-area="User" asp-controller="UserHome" asp-action="Index" class="nav-link text-dark"><span>Home</span></a></li>
                        @{
                            if (roles[0] == "Admin") {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminHome" asp-action="Index">Admin Panel</a>
                                </li>
                            }
                        }

                        <li class="nav-item"><a asp-controller="UserHome" asp-area="User" asp-action="BookHistory" class="nav-link text-dark"><span>Book History</span></a></li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">LMS</h2>
                        <p>
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil
                            repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae
                            harum esse fugiat. Itaque, culpa?
                        </p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li<a href="#"></a></li>
                            <li<a href="#"></a></li>
                            <li<a href="#"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md" style="margin-left: 120px;">
                    <div class="ftco-footer-widget mb-4 ml-md-4">
                        <h2 class="ftco-heading-2">Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Book History</a></li>
                            <li><a href="#">Search</a></li>
                            <li><a href="#">Log Out</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Question?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="text"> Ferizaj, Republika e Kosoves</span></li>
                                <li><a href="#">+383 123456</span></a></li>
                                <li><a href="#"><span class="text">info@lsm.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                    <p>Marigona Kadriu, Besmir Miftari, Jon Morina</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>