Library Managment/Library Managment/Areas/Admin/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_Managment.Data;
using Library_Managment.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Authorization;
using Library_Managment.Areas.Admin.Models;

namespace Library_Managment.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IHostingEnvironment _hostingEnvironment;
        public BooksController(ApplicationDbContext context, IHostingEnvironment hostingEnvironment) {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Admin/Books
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["Author"] = sortOrder == "author_desc" ? "author_asc" : "author_desc";
            ViewData["Date"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";


            if (searchString != null) {
                pageNumber = 1;
            } else {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var books = from s in _context.Books
                        select s;
            if (!String.IsNullOrEmpty(searchString)) {
                books = books.Where(s => s.Author.Contains(searchString)
                                       || s.Name.Contains(searchString));
            }
            switch (sortOrder) {
                case "name_desc":
                    books = books.OrderBy(s => s.Name);
                    break;
                case "author_desc":
                    books = books.OrderByDescending(s => s.Author);
                    break;
                case "author_asc":
                    books = books.OrderBy(s => s.Author);
                    break;
                case "date_desc":
                    books = books.OrderByDescending(s => s.PublishDate);
                    break;
                case "date_asc":
                    books = books.OrderBy(s => s.PublishDate);
                    break;
                default:
                    books = books.OrderBy(s => s.ISBN);
                    break;
            }

            int pageSize = 8;
            return View(await PaginatedList<Book>.CreateAsync(books.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        //
        // GET: Admin/Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Admin/Books/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ISBN,Name,Description,Genre,Author,PublishDate,Image,Amount,Available")] BookImagePath model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (model.Image != null) {
                    string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "BookImages");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Image.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    model.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                var book = new Book {
                    Name = model.Name,
                    ISBN = model.ISBN,
                    Description = model.Description,
                    Genre = model.Genre,
                    Author = model.Author,
                    PublishDate = model.PublishDate,
                    Image = uniqueFileName,
                    Amount = model.Amount,
                    Available = model.Available
                };

                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Admin/Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            BookImagePath bookModel = new BookImagePath {
                Id = book.Id,
                ISBN = book.ISBN,
                Name = book.Name,
                Description = book.Description,
                Genre = book.Genre,
                Author = book.Author,
                PublishDate = book.PublishDate,
                Amount = book.Amount,
                Available = book.Available

            };

            return View(bookModel);
        }

        // POST: Admin/Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ISBN,Name,Description,Genre,Author,PublishDate,Image,Amount,Available")] BookImagePath book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string uniqueFileName = null;
                    if (book.Image != null) {
                        string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "BookImages");
                        uniqueFileName = Guid.NewGuid().ToString() + "_" + book.Image.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        book.Image.CopyTo(new FileStream(filePath, FileMode.Create));
                    }

                    Book insertBook = new Book {
                        Id = book.Id,
                        ISBN = book.ISBN,
                        Name = book.Name,
                        Description = book.Description,
                        Genre = book.Genre,
                        Author = book.Author,
                        PublishDate = book.PublishDate,
                        Image = uniqueFileName,
                        Amount = book.Amount,
                        Available = book.Available
                    };

                    _context.Update(insertBook);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Admin/Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Admin/Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Books.FindAsync(id);
            _context.Books.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Books.Any(e => e.Id == id);
        }

        public async Task<IActionResult> GiveBook(string sortOrder, string currentFilter, string searchString, int? pageNumber, int id) {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null) {
                pageNumber = 1;
            } else {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var users = from s in _context.Users
                        select s;
            if (!String.IsNullOrEmpty(searchString)) {
                users = users.Where(s => s.Name.Contains(searchString)
                                       || s.Surname.Contains(searchString) || s.Email.Contains(searchString) || s.UserName.Contains(searchString));
            }
            switch (sortOrder) {
                case "name_desc":

Library Managment/Library Managment/Areas/Admin/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_Managment.Data;
using Library_Managment.Models;
using Microsoft.AspNetCore.Authorization;
using Library_Managment.Areas.Admin.Models;

namespace Library_Managment.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ContactsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Contacts
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var contacts = from c in _context.Contacts
                        select c;
 
            int pageSize = 10;
            return View(await PaginatedList<Contact>.CreateAsync(contacts.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Admin/Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Admin/Contacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
 
        // GET: Admin/Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contacts
                .FirstOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Admin/Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contacts.FindAsync(id);
            _context.Contacts.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactExists(int id)
        {
            return _context.Contacts.Any(e => e.ContactId == id);
        }
    }
}

Library Managment/Library Managment/Areas/User/Controllers/UserHomeController.cs
using Library_Managment.Data;
using Library_Managment.Models;
using Library_Managment.Areas.User.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TakenBooks = Library_Managment.Areas.User.Models.TakenBooks;
using Library_Managment.Data.Migrations;
using Library_Managment.Models;
using Library_Managment.Areas.Admin.Models;


namespace Library_Managment.Areas.User.Controllers {

    [Area("User")]
    [Authorize]
    public class UserHomeController : Controller {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<UserNewData> _userManager;
        public UserHomeController(ApplicationDbContext context,UserManager<UserNewData> userManager) {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> IndexAsync(string sortOrder, string currentFilter,string searchString, int? pageNumber) {

     
            List<Book> NewestBooks = (List<Book>)_context.Books.OrderByDescending(x => x.Id).Take(8).ToList<Book>();
            ViewBag.NewestBooks = NewestBooks;

            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
           /* ViewData["Author"] = sortOrder == "author_desc" ? "author_asc" : "author_desc";*/
            ViewData["Drama"] = sortOrder == "Drama" ? "Drama" : "Drama";
            ViewData["Romance"] = sortOrder == "Romance" ? "Romance" : "Romance";
            ViewData["Thriller"] = sortOrder == "Thriller" ? "Thriller" : "Thriller";
            ViewData["Biography"] = sortOrder == "Biography" ? "Biography" : "Biography";

            var books = from s in _context.Books
                        select s;
            switch (sortOrder) {
                case "Drama":
                    books = books.Where(s => s.Genre == "Drama") ;
                    break;
                case "Thriller":
                    books = books.Where(s => s.Genre == "Thriller");
                    break;
                case "Biography":
                    books = books.Where(s => s.Genre == "Biography");
                    break;
                case "Romance":
                    books = books.Where(s => s.Genre == "Romance");
                    break;
                default:
                    books = books;
                    break;
            }

            int pageSize = 8;
            return View(await PaginatedList<Book>.CreateAsync(books.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> BookHistoryAsync() {


            var current = await _userManager.GetUserAsync(User);

            var userRows = _context.TakenBooks.OrderByDescending(x => x.Id).Where(x => x.UserId == current.Id);


            List<TakenBooks> books = new List<TakenBooks>();


            foreach (var row in userRows) {
                var book = _context.Books.Find(row.BookId);

                TakenBooks temp = new TakenBooks {
                    Id = book.Id,
                    ISBN = book.ISBN,
                    Name = book.Name,
                    Description = book.Description,
                    Genre = book.Genre,
                    Author = book.Author,
                    PublishDate = book.PublishDate,
                    Image = book.Image,
                    Amount = book.Amount,
                    Available = book.Available,
                    TakenDate = row.TakenDate,
                    ReturnDate = row.ReturnDate
                };

                books.Add(temp);
            }

            return View(books);
        }

        [HttpPost]
        public IActionResult SearchBook(string searchtext) {
           
            List<Book> books = _context.Books.FromSqlRaw($"SELECT * FROM Books WHERE Name LIKE '%{searchtext}%' OR Author LIKE '%{searchtext}%'").ToList<Book>();

           if(books.Count == 0 || searchtext == null || searchtext.Length <=1) {
                return View("404");
            }

            return View("SearchResults",books);
        }

        public IActionResult BookDetails(int id) {
            Book book = _context.Books.Find(id);
            return View(book);
        }
    }
}

Library Managment/Library Managment/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library_Managment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/admin.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@1,700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light navbar-toggleable-sm ftco_navbar bg-light" id="navcstm" style="box-shadow: 0px 1px grey;">
            <div class="container">
                <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="User" asp-controller="UserHome" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AdminHome" asp-action="DisplayUsers">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contacts" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profile</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-item btn btn-light">Logout</button>
                            </form>
                        </li>
                    </ul>  
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">LMS</h2>
                        <p>
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil
                            repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae
                            harum esse fugiat. Itaque, culpa?
                        </p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li<a href="#"></a></li>
                            <li<a href="#"></a></li>
                            <li<a href="#"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md" style="margin-left: 120px;">
                    <div class="ftco-footer-widget mb-4 ml-md-4">
                        <h2 class="ftco-heading-2">Links</h2>
                        <ul class="list-unstyled">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Book History</a></li>
                            <li><a href="#">Search</a></li>
                            <li><a href="#">Log Out</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have a Question?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="text"> Ferizaj, Republika e Kosoves</span></li>
                                <li><a href="#">+383 123456</span></a></li>
                                <li><a href="#"><span class="text">info@lsm.com</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                    <p>Marigona Kadriu, Besmir Miftari, Jon Morina</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>